name: Test

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.7', '3.0' ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: RuboCop
      run: bundle exec rake rubocop

    - name: RSpec
      run: bundle exec dotenv -f ".env.test" rake spec
